services:
    influxdb:
        image: influxdb:2.0.7
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: iot
            DOCKER_INFLUXDB_INIT_BUCKET: users_business_events
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
        ports:
            - "8086:8086"
        volumes:
            - ./db:/docker-entrypoint-initdb.d
    app:
        build: ./app
        ports:
            - "8080:8080"
        environment:
            DB_URL: http://influxdb:8086
            INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
            INFLUXDB_ORG: iot   
            INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
        depends_on:
            - influxdb
    grafaha:
        image: grafana/grafana-oss:main
        ports:
            - 3000:3000

    nginx:
        image: nginx
        ports:
            - "80:80"